### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by WebCodePoet** [smeinecke/signing-milter#2]
Just a detail about your guide, you need to update the link?

root@server:/tmp# wget https://github.com/smeinecke/signing-milter/releases/latest/download/signing-milter_20220416-bullseye_amd64.deb
dpkg -i signing-milter_20220416-bullseye_amd64.deb
--2023-05-29 12:04:28--  https://github.com/smeinecke/signing-milter/releases/latest/download/signing-milter_20220416-bullseye_amd64.deb
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/smeinecke/signing-milter/releases/download/20220416/signing-milter_20220416-bullseye_amd64.deb [following]
--2023-05-29 12:04:28--  https://github.com/smeinecke/signing-milter/releases/download/20220416/signing-milter_20220416-bullseye_amd64.deb
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2023-05-29 12:04:28 ERROR 404: Not Found.

dpkg: error: cannot access archive 'signing-milter_20220416-bullseye_amd64.deb': No such file or directory

**Comment by smeinecke** [comment]
Sorry, URL has been updated in the README.
