### ISSUE TITLE
Debian 12 Support

### ISSUE THREAD

**Issue by coredirigent** [smeinecke/signing-milter#3]
Hello,

currently there is no support for Debian 12 as there is not libssl 1.1 on this Distribution.

Can you please add support?

Thank you for your efforts.

**Comment by APachLv** [comment]
Hi.

Please add  support for Debian 12.

Thanks.

**Comment by smeinecke** [comment]
added https://github.com/smeinecke/signing-milter/releases/download/20220416/signing-milter_20220426-bookworm_amd64.deb
